config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :users, only: [:show]
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.
  resources :balls do
    resources :likes, only: [:create, :destroy]
  end
  root 'balls#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/ball.rb
class Ball < ApplicationRecord
# 追記ここから
mount_uploader :image, ImageUploader
mount_uploader :video, VideoUploader

# 追記ここまで
belongs_to :user
has_many :likes, dependent: :destroy
has_many :liked_users, through: :likes, source: :user

end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :ball
  belongs_to :user
  validates_uniqueness_of :ball_id, scope: :user_id
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
         has_many :tweets , dependent: :destroy
         has_many :likes, dependent: :destroy
         has_many :liked_balls, through: :likes, source: :ball
         def already_liked?(ball)
          self.likes.exists?(ball_id: ball.id)
         end 
         has_many :balls, dependent: :destroy #追記 ユーザーが削除されたら、ツイートも削除されるようになります。すでに書いてある場合は追記しなくて大丈夫です。
         validates :name, presence: true #追記
         validates :profile, length: { maximum: 200 } #追記
         mount_uploader :image, ImageUploader
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    before_action :configure_permitted_parameters, if: :devise_controller?

  protected
  def configure_permitted_parameters
    # サインアップ時にnameのストロングパラメータを追加
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name, :image])
    # アカウント編集の時にnameとprofileのストロングパラメータを追加
    devise_parameter_sanitizer.permit(:account_update, keys: [:name, :profile, :image])
  end
 
end

app/controllers/balls_controller.rb
class BallsController < ApplicationController
    # 追加箇所
  before_action :authenticate_user!, only: [:new, :create]
  # ここまで
  #追加箇所
  def index
    if params[:search] != nil && params[:search] != ''
      #部分検索かつ複数検索
      search = params[:search]
      @balls = Ball.joins(:user).where("body LIKE ? OR user_id LIKE ?", "%#{search}%", "%#{search}%")
    else
      @balls = Ball.all
    end
  end

 # ここまで
    #追加箇所
def new
    @ball = Ball.new
  end

  def create
    ball = Ball.new(ball_params)
    ball.user_id = current_user.id
    if ball.save
      redirect_to :action => "index"
    else
      redirect_to :action => "new"
    end
  end

  def show
    @ball = Ball.find(params[:id])
  end

  def edit
    @ball = Ball.find(params[:id])
  end

  def update
    ball = Ball.find(params[:id])
    if ball.update(ball_params)
      redirect_to :action => "show", :id => ball.id
    else
      redirect_to :action => "new"
    end
  end

  def destroy
    ball = Ball.find(params[:id])
    ball.destroy
    redirect_to action: :index
  end

  private
  def ball_params
    params.require(:ball).permit(:body, :address, :title, :teamname, :image, :video, :lat,:lng)
  end

 #ここまで
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
    def create
        like = current_user.likes.create(ball_id: params[:ball_id]) #user_idとball_idの二つを代入
        redirect_back(fallback_location: new_ball_path)
      end
    
      def destroy
        like = Like.find_by(ball_id: params[:ball_id], user_id: current_user.id)
        like.destroy
        redirect_back(fallback_location: new_ball_path)
      end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
    def show
        @user = User.find(params[:id]) 
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/balls_helper.rb
module BallsHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/balls/edit.html.erb
<%= form_for @ball do |f| %>
 <div class ="editbox">
    <%= f.label :body %>
    <%= f.text_field :body, :size => 200 %> 
 </div>

 <div class ="editbox">
    <%= f.label :私の選ぶMVP %>
    <%= f.text_field :title, :size => 30 %>
 </div>

 <div class ="editbox">
    <%= f.label :今日の対戦チーム  %>
    <%= f.select :teamname, 
    [["ベガルタ仙台", "ベガルタ仙台"], 
    ["ブラウブリッツ秋田", "ブラウブリッツ秋田"],
    ["いわきFC", "いわきFC"],
    ["水戸ホーリーホック", "水戸ホーリーホック"],
    ["栃木SC", "栃木SC"],
    ["ザスパクサツ群馬", "ザスパクサツ群馬"],
    ["大宮アルディージャ", "大宮アルディージャ"],
    ["ジェフユナイテッド千葉", "ジェフユナイテッド千葉"],
    ["東京ヴェルディ", "東京ヴェルディ"],
    ["FC町田ゼルビア", "FC町田ゼルビア"],
    ["ヴァンフォーレ甲府", "ヴァンフォーレ甲府"],
    ["ツエーゲン金沢", "ツエーゲン金沢"],
    ["清水エスパルス", "清水エスパルス"],
    ["ジュビロ磐田", "ジュビロ磐田"],
    ["藤枝MYFC", "藤枝MYFC"],
    ["ファジアーノ岡山", "ファジアーノ岡山"],
    ["レノファ山口FC", "レノファ山口FC"],
    ["徳島ヴォルティス", "徳島ヴォルティス"],
    ["V・ファーレン長崎", "V・ファーレン長崎"],
    ["ロアッソ熊本", "ロアッソ熊本"],
    ["大分トリニータ", "大分トリニータ"]], include_blank: "対戦チームを選択" %>
 </div>

 <div class ="editbox">
    <%= f.label :今日のワンショット %>
    <%= f.file_field :image %>
 </div>

 <div class ="editbox">
    <%= f.label :投稿の説明  %>
    <%= f.text_area :body, :size => "30x2" %>
    <%= f.submit "編集する" %>
 </div>

  <% end %>

app/views/balls/index.html.erb
<div class="index">
  <div class="match-result">
    <date> 試合結果 </date>
    <score-1> 1 </score>
    <score-2> 1 </score>
    <div class="team-logo1">
      <img src="https://www.montedioyamagata.jp/wp-content/themes/montedio/assets/img/emblem/yamagata.png" width="500" height="589" alt="写真">
    </div>

    <div class="team-logo2">
      <img src="https://jleague.r10s.jp/img/common/img_club_akita.png" width="300" height="300" alt="写真">
    </div>

  </div>

  <div class="next-match">
    <n-match> NEXT MATCH </n-match>
    <detail> 
      09/29 NDソフトスタジアム山形
    </detail>

    <div class="team-logo3">
      <img src="https://jleague.r10s.jp/img/common/img_club_tokushima.png" width="300" height="300" alt="写真">
    </div>

    <div class="team-logo4">
      <img src="https://www.montedioyamagata.jp/wp-content/themes/montedio/assets/img/emblem/yamagata.png" width="500" height="589" alt="写真">
    </div>

  </div>

 


  <h4>投稿を検索
    <%= form_tag({controller:"balls",action:"index"}, method: :get) do %>
      <%= text_field_tag :search %>
      <%= submit_tag '検索する'  %>
    <% end %>

  </h4>





   
 <div class="tweets-container">
    <% @balls.each do |t| %>

  
    <%= image_tag t.image_url, class: "auto-resize-image", resize: "780x480^", crop: "780x480+0+0" if t.image? %>
    <div class="index-title">
      <%= t.title %>
    </div>

    <div class="index-body">
      <%= t.body %>
    </div>

    <div class="index-adress">
      <%= t.address %>
    </div>

    <div class="heart-index">
      <% if user_signed_in? %>
        <% if current_user.already_liked?(t) %>
            <%= link_to ball_like_path(id: t.id, ball_id: t.id), method: :delete do %>
              <i class="fas fa-heart"></i><%= t.likes.count %> 
            <% end %>
        <% else %>
            <%= link_to ball_likes_path(id: t.id, ball_id: t.id), method: :post do %>
              <i class="far fa-heart"></i><%= t.likes.count %>
            <% end %>
        <% end %>

        
      <% end %>
    </div>


      <div class="delete">
        <%= link_to "詳細へ", ball_path(t.id) %>  
        <% if user_signed_in? && current_user.id == t.user_id %>
        <%= link_to "削除する", ball_path(t.id), method: :delete %>
        <% end %> 
      </div>
    <% end %>


    

  </div>
</div>


app/views/balls/new.html.erb
<h2>新規投稿ページ</h2>
<%= form_for @ball do |f| %>
<div class="new-post-box">
  
  
  <div style="mvp-post">
    <%= f.label :私の選ぶMVP %>
    
     <%= f.text_field :title, :size => 30 %>
    
  </div>



  <div style="play-team-post">
    <%= f.label :今日の対戦チーム  %>
    <%= f.select :teamname, 
    [["ベガルタ仙台", "ベガルタ仙台"], 
    ["ブラウブリッツ秋田", "ブラウブリッツ秋田"],
    ["いわきFC", "いわきFC"],
    ["水戸ホーリーホック", "水戸ホーリーホック"],
    ["栃木SC", "栃木SC"],
    ["ザスパクサツ群馬", "ザスパクサツ群馬"],
    ["大宮アルディージャ", "大宮アルディージャ"],
    ["ジェフユナイテッド千葉", "ジェフユナイテッド千葉"],
    ["東京ヴェルディ", "東京ヴェルディ"],
    ["FC町田ゼルビア", "FC町田ゼルビア"],
    ["ヴァンフォーレ甲府", "ヴァンフォーレ甲府"],
    ["ツエーゲン金沢", "ツエーゲン金沢"],
    ["清水エスパルス", "清水エスパルス"],
    ["ジュビロ磐田", "ジュビロ磐田"],
    ["藤枝MYFC", "藤枝MYFC"],
    ["ファジアーノ岡山", "ファジアーノ岡山"],
    ["レノファ山口FC", "レノファ山口FC"],
    ["徳島ヴォルティス", "徳島ヴォルティス"],
    ["V・ファーレン長崎", "V・ファーレン長崎"],
    ["ロアッソ熊本", "ロアッソ熊本"],
    ["大分トリニータ", "大分トリニータ"]], include_blank: "対戦チームを選択", :size => 30 %>
  </div>
 

   
  
   
  <div style="picture-post">
    <%= f.label :今日のワンショット %>
    <%= f.file_field :image %>
  </div>
 
  
  
  <div style="explain-post">
    <%= f.label :投稿の説明  %>
    <%= f.text_area :body, :size => "30x2" %>
  </div>
  
  <div style="video-post">
    <%= f.label :video %>
    <%= f.file_field :video, :accept => 'video/*' %>
  </div>

  <div style="google-map">
    <%= f.label :lat,"緯度" %>
    <%= f.text_field :lat,:value =>"緯度", id: :lat %>
    <%= f.label :lng,"経度" %>
    <%= f.text_field :lng,:value =>"経度", id: :lng %>
  </div>

</div>


</div>


<br>
  <%= f.submit "投稿する",class:"new-post"%>
 
<% end %>

<div class="back">
 <%= link_to "投稿一覧に戻る", balls_path %>
</div>

<div class="30">
 <h3>開催スタジアム</h3>

  <div class="stadiam">
    <input id="address" type="textbox" value="ここに入力">
    <input type="button" value="スタジアムを検索" onclick="codeAddress()">
    <p40>マーカーをドラック＆ドロップで位置の調整ができます。<p40>
  </div>
  
<div id='map'></div>



  <style>
    #map {
      height: 350px;
      width: 700px;
      position: relative;
      bottom: 200px;
      left: 700px;


    }
  </style>


  <script>
  //初期マップの設定
  let map
  let marker
  function initMap(){
    geocoder = new google.maps.Geocoder()

    map = new google.maps.Map(document.getElementById('map'), {
      center:  {lat: 35.6803997, lng:139.7690174},  //東京
      zoom: 15,
      
    });
  }

  //検索後のマップ作成
  let geocoder
  let aft
  function codeAddress(){
    let inputAddress = document.getElementById('address').value;
    geocoder.geocode( { 'address': inputAddress}, function(results, status) {
      if (status == 'OK') {
          //マーカーが複数できないようにする
          if (aft == true){
              marker.setMap(null);
          }

          //新しくマーカーを作成する
          map.setCenter(results[0].geometry.location);
              marker = new google.maps.Marker({
              map: map,
              position: results[0].geometry.location,
              draggable: true	// ドラッグ可能にする
          });

          //二度目以降か判断
          aft = true

          //検索した時に緯度経度を入力する
          document.getElementById('lat').value = results[0].geometry.location.lat();
          document.getElementById('lng').value = results[0].geometry.location.lng();

          // マーカーのドロップ（ドラッグ終了）時のイベント
          google.maps.event.addListener( marker, 'dragend', function(ev){
              // イベントの引数evの、プロパティ.latLngが緯度経度
              document.getElementById('lat').value = ev.latLng.lat();
              document.getElementById('lng').value = ev.latLng.lng();
          });
      } else {
        alert('該当する結果がありませんでした：' + status);
      }
    });   
  }

  </script>
  <script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyCjXcA0P6kv1l2KRpdEBgpd9YxeEdhPAgw&callback=initMap" async defer></script>
</div>


  

app/views/balls/show.html.erb

<h6 style="margin-top: 30px;margin-bottom: 40px;">投稿詳細</h6>

<div class="show">
  <div class="show-body">
  <%= @ball.body %>
  </div>

  <div class="show-at">
  <%= @ball.created_at %>
  </div>

  <div class="show-teamname">
  <%= @ball.teamname %>
  </div>

  <div class="show-title">
  <%= @ball.title %>
  </div>

  <div class="show-image">
  <%= image_tag @ball.image_url, class: "auto-resize-image-2", resize: "780x480^", crop: "780x480+0+0" if @ball.image? %>
  </div>

  <div class="show-video">
    <%= link_to @ball.video_url.to_s do %>
      <%= video_tag @ball.video_url, class: "auto-resize-video-2", resize: "780x480^", crop: "780x480+0+0" if @ball.video? %>
    <% end %>
  </div>

  <div class="mvp-show">
   MVP
  </div>
 
  <div class="teamname-show">
   VS
  </div>
 
  <div class="body-show">
   今日の解説！
  </div>
  

</div>








<div class="like-user">
  <h10>いいねしたユーザー</h10>
  <h50>
    <% @ball.liked_users.each do |user| %>
      <li><%= user.email %></li>
    <% end %>
  </h50>
</div>

<div class="stadiam2">
    <input id="address" type="textbox" value="ここに入力">
    <input type="button" value="スタジアムを検索" onclick="codeAddress()">
    <p40>マーカーをドラック＆ドロップで位置の調整ができます。<p40>
</div>


<div class="stadiam-show">
 開催スタジアム
</div>


<div id='map'></div>

<style>
#map {
  height: 450px;
  width: 800px;
  position: relative;
  bottom: 500px;
  left: 600px;


}
</style>


<script>
//初期マップの設定
let map
let marker
function initMap(){
geocoder = new google.maps.Geocoder()

map = new google.maps.Map(document.getElementById('map'), {
  center:  {lat: 35.6803997, lng:139.7690174},  //東京
  zoom: 15,
  
});
}

//検索後のマップ作成
let geocoder
let aft
function codeAddress(){
let inputAddress = document.getElementById('address').value;
geocoder.geocode( { 'address': inputAddress}, function(results, status) {
  if (status == 'OK') {
      //マーカーが複数できないようにする
      if (aft == true){
          marker.setMap(null);
      }

      //新しくマーカーを作成する
      map.setCenter(results[0].geometry.location);
          marker = new google.maps.Marker({
          map: map,
          position: results[0].geometry.location,
          draggable: true	// ドラッグ可能にする
      });

      //二度目以降か判断
      aft = true

      //検索した時に緯度経度を入力する
      document.getElementById('lat').value = results[0].geometry.location.lat();
      document.getElementById('lng').value = results[0].geometry.location.lng();

      // マーカーのドロップ（ドラッグ終了）時のイベント
      google.maps.event.addListener( marker, 'dragend', function(ev){
          // イベントの引数evの、プロパティ.latLngが緯度経度
          document.getElementById('lat').value = ev.latLng.lat();
          document.getElementById('lng').value = ev.latLng.lng();
      });
  } else {
    alert('該当する結果がありませんでした：' + status);
  }
});   
}

</script>
<script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyCjXcA0P6kv1l2KRpdEBgpd9YxeEdhPAgw&callback=initMap" async defer></script>
</div>






<div class="image-video">

</div>

<div class="at-show">

</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Montedio</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <script src="https://kit.fontawesome.com/92ba495bca.js" crossorigin="anonymous"></script>
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Kosugi+Maru&display=swap" rel="stylesheet">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <header>
    <h1>Montedista</h1>
    <div class="header-list">
      <ul>
      <% if user_signed_in? %>
      <li><%= button_to 'ログアウト', destroy_user_session_path, method: :delete %></li>
    <% else %>
      <li><%= link_to "ログイン", new_user_session_path %></li>
    <% end %>
      <li><%= link_to "ホーム", balls_path %></li>
      <li><%= link_to "新規投稿",new_ball_path %></li>
      </ul>
    </div>

    <div class="index-mypage">
      <% if user_signed_in? %>
       <%= link_to "マイページへ", user_path(current_user.id) %>
      <% end %>
    </div>

    </header>
    <main>
    <%= yield %>
    </main>

  </body>
    
  
</html>

app/views/users/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation" data-turbo-cache="false">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/users/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= button_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider), data: { turbo: false } %><br />
  <% end %>
<% end %>

app/views/users/show.html.erb
<div class="mypage">
  <h8>マイページ</h8>
  <p1>ユーザーネーム : <%= @user.name %></p1>
  <p2>メールアドレス : <%= @user.email %></p2>
  <%= image_tag @user.image_url, class: "auto-resize-image3", resize: "780x480^", crop: "780x480+0+0" if @user.image? %>
</div>

<div class="mypage-edit">
  <% if current_user.id == @user.id %>
    <%= link_to "プロフィールを編集する", edit_user_registration_path %>
  <% end %>
</div>



<div class="mypage-all">
  <h15>あなたの投稿一覧</h15>
  <div class="my-post">
    <% @user.balls.each do |t| %>
      <p5><%= t.title %></p5>
      <p6><%= image_tag t.image_url, class: "auto-resize-image4", resize: "780x480^", crop: "780x480+0+0" if t.image? %></p6>
      
    <% end %>
  </div>
</div>

<!-- 以下はいいね機能を実装している場合-->


<div class="mypage-like">
  <h16>あなたがいいねした投稿一覧</h16>
  <% @user.liked_balls.each do |t| %>
    <div class="like-photo">
      <p9><%= image_tag t.image_url, class: "auto-resize-image5", resize: "780x480^", crop: "780x480+0+0" if t.image? %></p9>
      <p7><%= t.user.name %></p7>
    </div>
  <% end %>
</div>
<!-- ここまで-->

